name: walletly_app
description: walletly_app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sms: ^0.2.0
  http: ^0.12.0
  table_calendar:
  flutter_spinkit: ^3.1.0
  carousel_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.jpg


  fonts:
    - family: MaisonNeue
      fonts:
        - asset: assets/fonts/MaisonNeue-Medium.ttf
        - asset: assets/fonts/MaisonNeue-Book.ttf
          weight: 700
        - asset: assets/fonts/MaisonNeue-Bold.ttf
          weight: 900

